### ISSUE TITLE
Use destructuring

### ISSUE THREAD

**Issue by peBetrator** [cristijigau/Giphy-API-Search-Engine#3]
https://github.com/cristijigau/Giphy-API-Search-Engine/blob/896e8f644be5361abc6153f051923fc4649b1e9d/js/index.js#L20

Pls try using ES6+ approach - destructuring function arguments. For info relate here https://javascript.info/destructuring-assignment
Besides the code example from above, you should be using it also for object desctructuring (see line 73 with `img` variable)

**Comment by cristijigau** [comment]
fixed
