### ISSUE TITLE
Wrong init assignment 

### ISSUE THREAD

**Issue by peBetrator** [cristijigau/Giphy-API-Search-Engine#4]
https://github.com/cristijigau/Giphy-API-Search-Engine/blob/896e8f644be5361abc6153f051923fc4649b1e9d/js/index.js#L15

`receivedData` is initially assigned to array, but used as object in future. Pls try keeping your code well maintained, even though you are not using typescript, when reading vanilla js initial assignation misleads in that case

**Comment by cristijigau** [comment]
fixed
