### ISSUE TITLE
XMLHttpRequest is 👴

### ISSUE THREAD

**Issue by peBetrator** [cristijigau/Giphy-API-Search-Engine#5]
https://github.com/cristijigau/Giphy-API-Search-Engine/blob/896e8f644be5361abc6153f051923fc4649b1e9d/js/index.js#L50

XMLHttpRequest is good, but a liiiitle bit outdated. Not to copy and paste a lot of info, try reading this blog https://medium.com/beginners-guide-to-mobile-web-development/the-fetch-api-2c962591f5c#:~:text=According%20to%20Google%20Developers%20Documentation,than%20with%20the%20older%20XMLHttpRequest%20.&text=The%20main%20difference%20between%20Fetch,Promises%2C%20hence%20avoiding%20callback%20hell.
Pls try using fetch/axios

**Comment by cristijigau** [comment]
fixed
