### ISSUE TITLE
Object's property chaining is way too long

### ISSUE THREAD

**Issue by peBetrator** [cristijigau/Giphy-API-Search-Engine#7]
https://github.com/cristijigau/Giphy-API-Search-Engine/blob/896e8f644be5361abc6153f051923fc4649b1e9d/js/index.js#L87

Received data here relies on the response from BE/third party service. What happens if any of property from the chain is not provided from BE??? The answer is - your app dies :( Pls try somehow handle that stuff, so you won't need to fix any bugs from future
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by cristijigau** [comment]
fixed
