### ISSUE TITLE
Squash styles

### ISSUE THREAD

**Issue by peBetrator** [cristijigau/Giphy-API-Search-Engine#8]
https://github.com/cristijigau/Giphy-API-Search-Engine/blob/896e8f644be5361abc6153f051923fc4649b1e9d/css/style.css#L15
https://github.com/cristijigau/Giphy-API-Search-Engine/blob/896e8f644be5361abc6153f051923fc4649b1e9d/css/style.css#L20

You have to same class names, pls squash them

**Comment by cristijigau** [comment]
fixed
